@startuml context.puml
title Livestock Monitoring System - Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml


' Single farm boundary

System_Boundary(farm, "Local Farm Management System") {
  Person(farm_supervisor, "Livestock Supervisor", "Manages and monitors livestock health and location")

  System(lms, "Livestock Monitoring System", "Monitors livestock health and location using IoT devices")
  System_Ext(ext_notifications, "Local Notification Service", "Sends alerts and notifications")

  Rel(lms, ext_notifications, "Sends alerts and notifications")
  Rel(ext_notifications, farm_supervisor, "Sends alerts and notifications")
  Rel(farm_supervisor, lms, "Monitors")
}

' Central system boundary

System_Boundary(central_system, "Central Management System") {
  Person(farm_manager, "Farm Operations Manager", "Manages multiple farms")
  Person(bi, "Business Analyst", "Analyzes metrics")

  System(lms_central, "Central Livestock Monitoring System", "Aggregates data from multiple farms for centralized monitoring")

  Rel(farm_manager, lms_central, "Oversees multiple farms")
  Rel(bi, lms_central, "Analyzes")
}

' Inter-system relationships

Rel(lms, lms_central, "Syncs data with")


@enduml
